apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      volumes:
        - name: elastic-storage
          persistentVolumeClaim:
              claimName: elastic-pvc
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.8.11
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 9200
              name: client
            - containerPort: 9300
              name: nodes
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elastic-storage
          env:
            - name: discovery.type
              value: single-node
