apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-prime
spec:
  selector:
    matchLabels:
      app: mongodb-prime
  template:
    metadata:
      labels:
        app: mongodb-prime
    spec:
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: mongodb-prime
          image: mongo
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-storage
          env:
            - name: MONGO_LOG_DIR
              value: "/dev/null"
            - name: MONGO_DATA_DIR
              value: "/data/db"
            - name: MONGO_INITDB_DATABASE
              value: "prime"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "admin"
      
